### ISSUE TITLE
An error occurs when starting the program

### ISSUE THREAD

**Issue by PopRang** [p-vorobyev/spring-boot-starter-telegram#19]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'telegramClientApplication': Unsatisfied dependency expressed through field 'telegramClient': Error creating bean with name 'telegramClient' defined in class path resource [dev/voroby/springframework/telegram/TelegramClientAutoConfiguration.class]: Failed to instantiate [dev.voroby.springframework.telegram.client.TelegramClient]: Factory method 'telegramClient' threw exception with message: 'dev.voroby.springframework.telegram.client.TdApi$Object dev.voroby.springframework.telegram.client.Client.nativeClientExecute(dev.voroby.springframework.telegram.client.TdApi$Function)'
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:776) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:756) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:497) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1414) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:949) ~[spring-context-6.0.17.jar:6.0.17]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:615) ~[spring-context-6.0.17.jar:6.0.17]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.9.jar:3.1.9]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.9.jar:3.1.9]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.9.jar:3.1.9]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) ~[spring-boot-3.1.9.jar:3.1.9]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-3.1.9.jar:3.1.9]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.9.jar:3.1.9]
	at dev.voroby.springframework.telegram.TelegramClientApplication.main(TelegramClientApplication.java:21) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegramClient' defined in class path resource [dev/voroby/springframework/telegram/TelegramClientAutoConfiguration.class]: Failed to instantiate [dev.voroby.springframework.telegram.client.TelegramClient]: Factory method 'telegramClient' threw exception with message: 'dev.voroby.springframework.telegram.client.TdApi$Object dev.voroby.springframework.telegram.client.Client.nativeClientExecute(dev.voroby.springframework.telegram.client.TdApi$Function)'
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:773) ~[spring-beans-6.0.17.jar:6.0.17]
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.voroby.springframework.telegram.client.TelegramClient]: Factory method 'telegramClient' threw exception with message: 'dev.voroby.springframework.telegram.client.TdApi$Object dev.voroby.springframework.telegram.client.Client.nativeClientExecute(dev.voroby.springframework.telegram.client.TdApi$Function)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.17.jar:6.0.17]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:646) ~[spring-beans-6.0.17.jar:6.0.17]
	... 33 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: 'dev.voroby.springframework.telegram.client.TdApi$Object dev.voroby.springframework.telegram.client.Client.nativeClientExecute(dev.voroby.springframework.telegram.client.TdApi$Function)'
	at dev.voroby.springframework.telegram.client.Client.nativeClientExecute(Native Method) ~[classes/:na]
	at dev.voroby.springframework.telegram.client.Client.execute(Client.java:117) ~[classes/:na]
	at dev.voroby.springframework.telegram.client.TelegramClient.initializeNativeClient(TelegramClient.java:125) ~[classes/:na]
	at dev.voroby.springframework.telegram.client.TelegramClient.<init>(TelegramClient.java:50) ~[classes/:na]
	at dev.voroby.springframework.telegram.TelegramClientAutoConfiguration.telegramClient(TelegramClientAutoConfiguration.java:62) ~[classes/:na]
	at dev.voroby.springframework.telegram.TelegramClientAutoConfiguration$$SpringCGLIB$$0.CGLIB$telegramClient$1(<generated>) ~[classes/:na]
	at dev.voroby.springframework.telegram.TelegramClientAutoConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.17.jar:6.0.17]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.17.jar:6.0.17]
	at dev.voroby.springframework.telegram.TelegramClientAutoConfiguration$$SpringCGLIB$$0.telegramClient(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.17.jar:6.0.17]
	... 34 common frames omitted

Process finished with exit code 1

**Comment by PopRang** [comment]
Please tell me what the problem is

**Comment by p-vorobyev** [comment]
Because of ` java.lang.UnsatisfiedLinkError` it seems that you have not linked `tdjni` library on starting program. Check that you applied step number 4 from installation doc. Each release has its own precompiled libraries that should be used with it.

**Comment by PopRang** [comment]
> 因为` java.lang.UnsatisfiedLinkError`您似乎在启动程序时没有链接`tdjni`库。检查您是否应用了安装文档中的步骤 4。每个版本都有自己的预编译库，应与其一起使用。

代码哪里有设置这个获取路径嘛

**Comment by p-vorobyev** [comment]
You need to add VM option `-Djava.library.path=<path_to_shared_library>` when starting program. You can get shared library in `libs` directory of the repository for specific platform.

**Comment by PopRang** [comment]
Thanks
Now I encounter a new problem. After logging in, the TG account will be blocked immediately. Have you also encountered this problem?

**Comment by p-vorobyev** [comment]
> Thanks Now I encounter a new problem. After logging in, the TG account will be blocked immediately. Have you also encountered this problem?

I haven't. Make sure you use your own `api-id` and `api-hash` and don't do direct logout or session deletion frequently.

**Comment by PopRang** [comment]
Use your own appid and hash, and your account will be banned overnight after logging in.

**Comment by p-vorobyev** [comment]
Unfortunately, I can't help you with the reason for your ban. It's better to contact telegram support, because there is no other way to figure it out.

> Use your own appid and hash, and your account will be banned overnight after logging in.

In my experience,  I use the TDLib-client every day with behaviour as regular user, and have never encountered such problems.

**Comment by PopRang** [comment]
okay, thank you

**Comment by PopRang** [comment]
Excuse me, do you know how to open db.sqlite? I use multiple tools to open it and it will prompt, file is not database

**Comment by PopRang** [comment]
@p-vorobyev Excuse me, do you know how to open db.sqlite? I use multiple tools to open it and it will prompt, file is not database

**Comment by p-vorobyev** [comment]
It's not possible to open db.sqlite outside the `tdjni` library process. It's encrypted by TDLib. All interactions, including offline requests, are performed using TdApi only.

**Comment by PopRang** [comment]
thank you

**Comment by PopRang** [comment]
Based on your project, I'm currently monitoring new messages from multiple accounts, but I can't identify which account the message is from (I don't see a specific unique identifier in the message body). Do you know how to do this?

**Comment by PopRang** [comment]
@p-vorobyev Based on your project, I'm currently monitoring new messages from multiple accounts, but I can't identify which account the message is from (I don't see a specific unique identifier in the message body). Do you know how to do this?

**Comment by p-vorobyev** [comment]
> @p-vorobyev Based on your project, I'm currently monitoring new messages from multiple accounts, but I can't identify which account the message is from (I don't see a specific unique identifier in the message body). Do you know how to do this?

`simple-client` is just a minimal example how to start using starter. You can use all the features of TDLib. See [getting started](https://core.telegram.org/tdlib/getting-started).

[Message](https://p-vorobyev.github.io/javadoc_spring-boot-starter-telegram/dev/voroby/springframework/telegram/client/TdApi.Message.html) object has a `senderId` which should help identify the sender(user or chat). You can get it with TDLib API or with templates beans(`UserTemplate`, `ChatTemplate`).

**Comment by PopRang** [comment]
Yes, I know that new messages have senderId. Now I create multiple clients to monitor the new messages received from multiple accounts. I don’t know how to distinguish which account they are from.

**Comment by p-vorobyev** [comment]
This starter is not designed to autoconfigure multiple client instances in single java process. But TDLib allows to do it. You can inject own `ResultHandler` for each new created instance of the client. It will let you know from what account object came from.
   But anyway, this is not related to this issue and project and can be moved to discussions.

**Comment by jackeyprince** [comment]
where do i get the spring.telegram.client.database-encryption-key from ？
